# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BackendJob
    displayName: BackendJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(BackendJob.SourcesDirectory)/backend/Dockerfile'
        tags: |
          $(tag)

#  - job: FrontendJob
#    displayName: FrontendJob
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#      - task: Docker@2
#        displayName: Build an image
#        inputs:
#          command: build
#          dockerfile: '$(FrontendJob.SourcesDirectory)/frontend/Dockerfile'
#          tags: |
#            $(tag)