version: '3.8'
services:
  backend:
    build: ./backend # Directory containing Dockerfile for backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydatabase

  frontend:
    build: ./frontend # Directory containing Dockerfile for frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  db:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

